In [64]:
import numpy as np

In [1]:
a = np.arange(0,15,1,dtype = np.float64).reshape(3,5)
print(a)
print("Shape: ",a.shape)
print("Data type: ",a.dtype)
print("Size: ",a.size)
print("Dimensions: ",a.ndim)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
Shape:  (3, 5)
Data type:  float64
Size:  15
Dimensions:  2


In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) #create 2d array
print(a.shape)

(3, 3)


In [4]:
# Create complex array
a = np.array([[1,2],[3,4]],dtype=complex)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


#### Various methods to create array in Numpy

In [12]:
a = np.linspace(0,10,11)
a = np.full((2,2),55)
a = np.full_like(a,12)
a = np.random.randint(2,size = 2)
a = np.random.randn(2,2)

#### Basic Operations

In [18]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print("a-b: ",a-b)

a-b:  [ 9 18 27 36]


In [19]:
p = np.power(b,2)
s = np.sin(b)
print("p: ",p)
print("s: ",s)

p:  [ 1  4  9 16]
s:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [21]:
print(a*b) # elementwise multiplication
print(a.dot(b)) # matrix product
print(a@b) # another matrix product

[ 10  40  90 160]
300
300


#### Indexing,Slicing and Iterating

###### 1D Arrays

In [25]:
a = np.arange(0,10)
print(a[1:3])

[1 2]


In [27]:
print(a[:6:2])

[0 2 4]


In [28]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


###### Multi-Dimensional Arrays

In [30]:
b = np.arange(0,20).reshape(4,5)
print(b[2,3])

13


In [31]:
print(b[0:1,:])

[[0 1 2 3 4]]


In [32]:
print(b[0:1])

[[0 1 2 3 4]]


In [33]:
print(b[3:4,:])

[[15 16 17 18 19]]


In [34]:
print(b[-1])

[15 16 17 18 19]


In [35]:
# Iterating
for row in b:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
# Iterating
for element in b.flat:
    print(element)

#### Reshaping

In [40]:
b = np.arange(0,20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
print(b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [39]:
print(b.reshape(5,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [41]:
print(b.T) # transpose of array

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


#### Hstack,Vstack and Hsplit and Vsplit

In [42]:
a = np.array([[1,2],[3,4]])

b = np.array([[10,20],[30,40]])

print(np.hstack((a,b)))

print(np.vstack((a,b)))

print(np.hsplit(a,2))

print(np.vsplit(b,2))

[[ 1  2 10 20]
 [ 3  4 30 40]]
[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]
[array([[1],
       [3]]), array([[2],
       [4]])]
[array([[10, 20]]), array([[30, 40]])]


#### Astype

In [43]:

a = np.arange(0,5)
print(a.dtype)

a = a.astype(np.float64)
print(a.dtype)

int64
float64


#### Manipulate Axis

In [44]:
# squeeze
a = np.ones(shape=(100,100,1,1),dtype=np.float64)
print(a.shape)

(100, 100, 1, 1)


In [49]:
b = np.squeeze(a.copy(),axis=2)
print(b.shape)

(100, 100, 1)


In [48]:
c = np.squeeze(a.copy())
print(c.shape)

(100, 100)


In [50]:
# expand_dims
a = np.ones(shape=(100,100,3))
print(a.shape)
b = np.expand_dims(a.copy(),axis=0)
print(b.shape)

(100, 100, 3)
(1, 100, 100, 3)


##### argmax,argmin,min,max

In [56]:
a = np.random.rand(6,)
print("a: ",a)
print("Argmax : ",np.argmax(a))
print("Max element: ",np.max(a))
print("Argmin: ",np.argmin(a))
print("Min element: ",np.min(a))

a:  [0.08000549 0.32227728 0.10738888 0.52939956 0.61696091 0.82732597]
Argmax :  5
Max element:  0.8273259689386491
Argmin:  0
Min element:  0.08000549425882619


#### Change order of dimensions in Numpy

In [58]:
a = np.arange(864).reshape(24,12,3)
print("Axis0: ",a.shape[0])
print("Axis1: ",a.shape[1])
print("Axis2: ",a.shape[2])

Axis0:  24
Axis1:  12
Axis2:  3


In [60]:
a = a.transpose(2,0,1)
print("Axis0: ",a.shape[0])
print("Axis1: ",a.shape[1])
print("Axis2: ",a.shape[2])

Axis0:  3
Axis1:  24
Axis2:  12
